'''
Q. You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
'''
# Ans :

def findTheDifference(s, t):
    result = 0
    for ch in s:
        result ^= ord(ch)

    for ch in t:
        result ^= ord(ch)

    return chr(result)

print(findTheDifference("abcd", "abcde"))
print(findTheDifference("", "y"))

